#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }
<#
Tests for lib/Test-SchemaVersion.ps1: shared helper that reads and validates
the SchemaVersion pragma on config.conf and hosts.conf. Backward compat
(absent pragma → v1) is the dominant case; the future-version warning path
is what actually exercises new code, so cover both.
#>

BeforeAll {
    $script:RepoRoot = Split-Path -Parent $PSScriptRoot
    . (Join-Path $script:RepoRoot 'lib\Test-SchemaVersion.ps1')

    function script:New-Config([hashtable]$Pairs) {
        $d = [System.Collections.Generic.Dictionary[string,string]]::new(
            [System.StringComparer]::OrdinalIgnoreCase)
        foreach ($k in $Pairs.Keys) { $d[$k] = "$($Pairs[$k])" }
        return $d
    }
}

Describe 'lib/Test-SchemaVersion.ps1' {

    Context 'Config artifact - absent pragma' {

        It 'treats absent SchemaVersion as v1 (backward compat with pre-v0.0.20 configs)' {
            $cfg = New-Config @{ SourceSharePath = '\\NAS\Share'; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 1 -ArtifactName 'config.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }

        It 'treats empty SchemaVersion value as absent (v1)' {
            $cfg = New-Config @{ SchemaVersion = ''; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 1 -ArtifactName 'config.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }
    }

    Context 'Config artifact - matching version' {

        It 'returns no warning when SchemaVersion matches the expected' {
            $cfg = New-Config @{ SchemaVersion = '1'; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 1 -ArtifactName 'config.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }
    }

    Context 'Config artifact - mismatch and parse failures' {

        It 'returns IsCompatible=false and an actionable warning when on-disk schema is newer than expected' {
            $cfg = New-Config @{ SchemaVersion = '5'; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 1 -ArtifactName 'config.conf'
            $result.ReadVersion     | Should -Be 5
            $result.ExpectedVersion | Should -Be 1
            $result.IsCompatible    | Should -BeFalse
            $result.Warning         | Should -Match 'v5'
            $result.Warning         | Should -Match 'v1'
            $result.Warning         | Should -Match 'config\.conf'
        }

        It 'returns IsCompatible=false and a parse-failure warning when SchemaVersion is not an integer' {
            $cfg = New-Config @{ SchemaVersion = 'one'; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 1 -ArtifactName 'config.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeFalse
            $result.Warning      | Should -Match "'one'"
            $result.Warning      | Should -Match 'not an integer'
        }

        It 'allows a lower on-disk schema (compatible)' {
            # Backward path: caller is built for v3, on-disk is v1 -> compatible.
            $cfg = New-Config @{ SchemaVersion = '1'; Port = '8080' }
            $result = Test-SchemaVersion -ConfigData $cfg -ExpectedVersion 3 -ArtifactName 'config.conf'
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }
    }

    Context 'Hosts artifact - pragma in header' {

        BeforeEach {
            $script:HostsPath = Join-Path $TestDrive 'hosts.conf'
        }

        It 'reads SchemaVersion: 1 from the auto-generated header' {
            @(
                '# =============================================================================',
                '# hosts.conf - AUTO-GENERATED by Update-DefenderOffline.ps1 v0.0.20',
                '# SchemaVersion: 1',
                '# Generated  : 2026-06-02',
                '# =============================================================================',
                '',
                'HOST01',
                'HOST02'
            ) | Set-Content -Path $script:HostsPath -Encoding UTF8

            $result = Test-SchemaVersion -HostsFilePath $script:HostsPath -ExpectedVersion 1 -ArtifactName 'hosts.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }

        It 'warns when hosts.conf advertises a newer schema than the caller expects' {
            @(
                '# hosts.conf',
                '# SchemaVersion: 7',
                'HOST01'
            ) | Set-Content -Path $script:HostsPath -Encoding UTF8

            $result = Test-SchemaVersion -HostsFilePath $script:HostsPath -ExpectedVersion 1 -ArtifactName 'hosts.conf'
            $result.ReadVersion  | Should -Be 7
            $result.IsCompatible | Should -BeFalse
            $result.Warning      | Should -Match 'v7'
        }

        It 'treats a missing pragma as v1 (backward compat with legacy hosts.conf)' {
            @(
                '# hosts.conf (legacy format, no pragma)',
                'HOST01',
                'HOST02'
            ) | Set-Content -Path $script:HostsPath -Encoding UTF8

            $result = Test-SchemaVersion -HostsFilePath $script:HostsPath -ExpectedVersion 1 -ArtifactName 'hosts.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }

        It 'ignores a pragma that appears outside the first 10 lines (protects against false positives in hostname data)' {
            $lines = @('# hosts.conf')
            for ($i = 1; $i -le 15; $i++) { $lines += "HOST$i" }
            $lines += '# SchemaVersion: 99'
            $lines | Set-Content -Path $script:HostsPath -Encoding UTF8

            $result = Test-SchemaVersion -HostsFilePath $script:HostsPath -ExpectedVersion 1 -ArtifactName 'hosts.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
        }

        It 'returns v1 when hosts.conf does not exist (no error)' {
            $missing = Join-Path $TestDrive 'no-hosts.conf'
            $result = Test-SchemaVersion -HostsFilePath $missing -ExpectedVersion 1 -ArtifactName 'hosts.conf'
            $result.ReadVersion  | Should -Be 1
            $result.IsCompatible | Should -BeTrue
            $result.Warning      | Should -BeNullOrEmpty
        }
    }
}
